# mattermost-s-mcp 설정 템플릿
# 실제 배포 시 이 값을 복사해 웹훅 URL을 채널별로 등록하세요.

version: 1
# 기본 채널명을 등록된 웹훅 목록 중 하나로 지정합니다.
default_channel: general

# 채널-웹훅 매핑 목록
webhooks:
  - channel: general
    url: https://your-mattermost-server.com/hooks/your-webhook-token-here
    description: 일반 채널
  - channel: alerts
    url: https://your-mattermost-server.com/hooks/another-webhook-token
    description: 알림 채널
